//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvilGenius.RxDataBindings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvilGenius.RxDataBindings.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed types of binding for this kind of target are {0}.
        /// </summary>
        internal static string RxDataBindings_allowed_types_binding_are_template {
            get {
                return ResourceManager.GetString("RxDataBindings_allowed_types_binding_are_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1} nothing to do here. Please define type of {0}.
        /// </summary>
        internal static string RxDataBindings_binding_mode_is_default_template {
            get {
                return ResourceManager.GetString("RxDataBindings_binding_mode_is_default_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property expression.
        /// </summary>
        internal static string RxDataBindings_invalidPropertyExpression {
            get {
                return ResourceManager.GetString("RxDataBindings_invalidPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mode is intended for using in {1}.
        /// </summary>
        internal static string RxDataBindings_misuse_of_firecommand_mode_template {
            get {
                return ResourceManager.GetString("RxDataBindings_misuse_of_firecommand_mode_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source to bind to.
        /// </summary>
        internal static string RxDataBindings_noSourceProperty {
            get {
                return ResourceManager.GetString("RxDataBindings_noSourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target proxy not set.
        /// </summary>
        internal static string RxDataBindings_noTargetProxy {
            get {
                return ResourceManager.GetString("RxDataBindings_noTargetProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value converter.
        /// </summary>
        internal static string RxDataBindings_noValueConverter {
            get {
                return ResourceManager.GetString("RxDataBindings_noValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is disposed.
        /// </summary>
        internal static string RxDataBindings_objIsDisposed {
            get {
                return ResourceManager.GetString("RxDataBindings_objIsDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This kind of source property support only {0}.
        /// </summary>
        internal static string RxDataBindings_src_prop_support_only_template {
            get {
                return ResourceManager.GetString("RxDataBindings_src_prop_support_only_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided type of target proxy is not supported.
        /// </summary>
        internal static string RxDataBindings_targetProxyNotSupported {
            get {
                return ResourceManager.GetString("RxDataBindings_targetProxyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to set unknown type of property.
        /// </summary>
        internal static string RxDataBindings_tryingSetUnknownProp {
            get {
                return ResourceManager.GetString("RxDataBindings_tryingSetUnknownProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of binding is {0} but expected to be {1}. Changing to the {1}.
        /// </summary>
        internal static string RxDataBindings_type_of_binding_expectedX_butY_template {
            get {
                return ResourceManager.GetString("RxDataBindings_type_of_binding_expectedX_butY_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string RxDataBindings_unknown {
            get {
                return ResourceManager.GetString("RxDataBindings_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not {0}.
        /// </summary>
        internal static string RxDataBindings_valueIsNot_template {
            get {
                return ResourceManager.GetString("RxDataBindings_valueIsNot_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided target proxy is not compatible with this source property type.
        /// </summary>
        internal static string RxDataBindings_WrongSourcePropertyType {
            get {
                return ResourceManager.GetString("RxDataBindings_WrongSourcePropertyType", resourceCulture);
            }
        }
    }
}
