#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EvilGenius.RxDataBindings.Android.Resource", IsApplication=false)]

namespace EvilGenius.RxDataBindings.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.3.3.31")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F010000
			public static int msg_empty_val_in_img_view_src = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int msg_generic_preference_trg = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int msg_unknown_visiblity = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int template_val_isnt_drawable = 2130771971;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
